imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    #translator:      { fallback: "%locale%" }
    translator:      { fallback: en }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
# doctrine:
#     dbal:
#         driver:   "%database_driver%"
#         host:     "%database_host%"
#         port:     "%database_port%"
#         dbname:   "%database_name%"
#         user:     "%database_user%"
#         password: "%database_password%"
#         charset:  UTF8
#         # if using pdo_sqlite as your database driver:
#         #   1. add the path in parameters.yml
#         #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
#         #   2. Uncomment database_path in parameters.yml.dist
#         #   3. Uncomment next line:
#         #     path:     "%database_path%"

#     orm:
#         auto_generate_proxy_classes: "%kernel.debug%"
#         auto_mapping: true

doctrine_mongodb:
    connections:
        default:
            server: mongodb://localhost:27017
            options: {}
    default_database: lifestutor_database
    document_managers:
        default:
            auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

# Lifestutor services
services:
    apikey_user_provider:
        class:     Lifestutor\StoreBundle\Security\ApiKeyUserProvider
        arguments: ["@doctrine_mongodb"]
    # apikey_authenticator:
    #     class:     Lifestutor\StoreBundle\Security\ApiKeyAuthenticator
    #     arguments: ["@apikey_user_provider"]
    kernel.listener.cors_response_listener:
        class: Lifestutor\StoreBundle\EventListener\CorsResponseListener
        tags:
            - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }

# Sensio Framework Extra Configuration
sensio_framework_extra:
    view: { annotations: false }
    # router: { annotations: true }
    # request: { converters: true }

# FOSRest
fos_rest:
    body_listener: true
    disable_csrf_role: ROLE_API
    format_listener:
        rules:
            - { path: ^/api, priorities: [ json, xml ], fallback_format: json, prefer_extension: false }
            - { path: ^/oauth, priorities: [ json, xml ], fallback_format: json, prefer_extension: false }
            - { path: ^/, priorities: [ html ], fallback_format: html, prefer_extension: false }
    exception:
        codes:
            'Lifestutor\StoreBundle\Exception\InvalidFormException': 400
            'Symfony\Component\Routing\Exception\ResourceNotFoundException': 404
            'Doctrine\ORM\OptimisticLockException': HTTP_CONFLICT
        messages:
            'Symfony\Component\Routing\Exception\ResourceNotFoundException': true
            'Lifestutor\StoreBundle\Exception\InvalidFormException': true
    # param_fetcher_listener: true
    # view:
    #     view_response_listener: 'force'
        # formats:
        #     xml:  true
        #     json: true
        # templating_formats:
        #     html: true
    # allowed_methods_listener: true
    # access_denied_listener:
    #     json: true

fos_oauth_server:
    db_driver: mongodb       # Driver availables: orm, mongodb, or propel
    client_class:        Lifestutor\OAuthServerBundle\Document\Client
    access_token_class:  Lifestutor\OAuthServerBundle\Document\AccessToken
    refresh_token_class: Lifestutor\OAuthServerBundle\Document\RefreshToken
    auth_code_class:     Lifestutor\OAuthServerBundle\Document\AuthCode
    service:
        user_provider: apikey_user_provider
        options:
            supported_scopes: user