lifestutor_inventory_book_all:
    pattern:  /v1/books
    defaults: { _controller: LifestutorInventoryBundle:Book:all, _format: ~ }
    requirements:
        _method: GET

lifestutor_inventory_book_options:
    pattern:  /v1/books
    defaults: { _controller: LifestutorInventoryBundle:Book:options, _format: ~ }
    requirements:
        _method: OPTIONS

lifestutor_inventory_post_book:
    pattern:  /v1/books
    defaults: { _controller: LifestutorInventoryBundle:Book:post, _format: ~ }
    requirements:
        _method: POST