lifestutor_inventory_book:
    pattern:  /v1/books/{id}
    defaults: { _controller: LifestutorInventoryBundle:Book:book, _format: ~ }
    requirements:
        _method: GET

lifestutor_inventory_book_edit_options:
    pattern:  /v1/books/{id}
    defaults: { _controller: LifestutorInventoryBundle:Book:options, _format: ~ }
    requirements:
        _method: OPTIONS

lifestutor_inventory_book_all:
    pattern:  /v1/books
    defaults: { _controller: LifestutorInventoryBundle:Book:all, _format: ~ }
    requirements:
        _method: GET

lifestutor_inventory_book_options:
    pattern:  /v1/books
    defaults: { _controller: LifestutorInventoryBundle:Book:options, _format: ~ }
    requirements:
        _method: OPTIONS

lifestutor_inventory_post_book:
    pattern:  /v1/books
    defaults: { _controller: LifestutorInventoryBundle:Book:post, _format: ~ }
    requirements:
        _method: POST

lifestutor_inventory_put_book:
    pattern:  /v1/books
    defaults: { _controller: LifestutorInventoryBundle:Book:update, _format: ~ }
    requirements:
        _method: PUT

lifestutor_inventory_delete_book:
    pattern:  /v1/books/{id}
    defaults: { _controller: LifestutorInventoryBundle:Book:delete, _format: ~ }
    requirements:
        _method: DELETE

lifestutor_inventory_patch_book:
    pattern:  /v1/books/{id}
    defaults: { _controller: LifestutorInventoryBundle:Book:patch, _format: ~ }
    requirements:
        _method: PATCH

lifestutor_inventory_upload_book:
    pattern:  /v1/books/upload/book
    defaults: { _controller: LifestutorInventoryBundle:Book:upload, _format: ~ }
    requirements:
        _method: POST

lifestutor_inventory_book_upload_options:
    pattern:  /v1/books/upload/book
    defaults: { _controller: LifestutorInventoryBundle:Book:options, _format: ~ }
    requirements:
        _method: OPTIONS

lifestutor_inventory_delete_book_photo:
    pattern:  /v1/books/delete/photo/{id}
    defaults: { _controller: LifestutorInventoryBundle:Book:delete_photo, _format: ~ }
    requirements:
        _method: DELETE

lifestutor_inventory_delete_book_photo_options:
    pattern:  /v1/books/delete/photo/{id}
    defaults: { _controller: LifestutorInventoryBundle:Book:options, _format: ~ }
    requirements:
        _method: OPTIONS

# Routes for website's access to inventory
lifestutor_inventory_storefont_catalog_all:
    pattern:  /v1/storefront/catalogs
    defaults: { _controller: LifestutorInventoryBundle:Storefrontcatalog:all, _format: ~ }
    requirements:
        _method: GET

lifestutor_inventory_storefont_catalog_options:
    pattern:  /v1/storefront/catalogs
    defaults: { _controller: LifestutorInventoryBundle:Storefrontcatalog:options, _format: ~ }
    requirements:
        _method: OPTIONS

# Catalog items
lifestutor_inventory_catalog_items:
    pattern:  /v1/catalog-items/{catalog_id}
    defaults: { _controller: LifestutorInventoryBundle:Item:catalog_items, _format: ~ }
    requirements:
        _method: GET

lifestutor_inventory_catalog_items_options:
    pattern:  /v1/catalog-items/{id}
    defaults: { _controller: LifestutorInventoryBundle:Item:options, _format: ~ }
    requirements:
        _method: OPTIONS