parameters:
    lifestutor_inventory.book.service.class: Lifestutor\InventoryBundle\Service\BookService
    lifestutor_inventory.book.class: Lifestutor\InventoryBundle\Document\Book

services:
    lifestutor_store.book.service:
        class:      "%lifestutor_inventory.book.service.class%"
        arguments:  ["@doctrine_mongodb", "%lifestutor_inventory.book.class%", "@form.factory"]