<?php

namespace Hydrators;

use Doctrine\ODM\MongoDB\DocumentManager;
use Doctrine\ODM\MongoDB\Mapping\ClassMetadata;
use Doctrine\ODM\MongoDB\Hydrator\HydratorInterface;
use Doctrine\ODM\MongoDB\UnitOfWork;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ODM. DO NOT EDIT THIS FILE.
 */
class FOSOAuthServerBundleDocumentClientHydrator implements HydratorInterface
{
    private $dm;
    private $unitOfWork;
    private $class;

    public function __construct(DocumentManager $dm, UnitOfWork $uow, ClassMetadata $class)
    {
        $this->dm = $dm;
        $this->unitOfWork = $uow;
        $this->class = $class;
    }

    public function hydrate($document, $data, array $hints = array())
    {
        $hydratedData = array();

        /** @Field(type="string") */
        if (isset($data['randomId'])) {
            $value = $data['randomId'];
            $return = (string) $value;
            $this->class->reflFields['randomId']->setValue($document, $return);
            $hydratedData['randomId'] = $return;
        }

        /** @Field(type="collection") */
        if (isset($data['redirectUris'])) {
            $value = $data['redirectUris'];
            $return = $value;
            $this->class->reflFields['redirectUris']->setValue($document, $return);
            $hydratedData['redirectUris'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['secret'])) {
            $value = $data['secret'];
            $return = (string) $value;
            $this->class->reflFields['secret']->setValue($document, $return);
            $hydratedData['secret'] = $return;
        }

        /** @Field(type="collection") */
        if (isset($data['allowedGrantTypes'])) {
            $value = $data['allowedGrantTypes'];
            $return = $value;
            $this->class->reflFields['allowedGrantTypes']->setValue($document, $return);
            $hydratedData['allowedGrantTypes'] = $return;
        }
        return $hydratedData;
    }
}